name: Trigger Jenkins Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Jenkins Build
      uses: actions/http-request@v2
      with:
        url: https://1232-59-96-56-57.ngrok-free.app/job/jenkins/build
        method: POST
        headers: |
          Authorization: Basic ${{ secrets.JENKINS_BASIC_AUTH }}
